sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download the sdk and install on little instance provided by travis CI
  - source $HOME/google-cloud-sdk/path.bash.inc # look out for default install google directory provided by sdk and run path.bash.inc
  - gcloud components update kubectl # install and update kubectl across our travis environment
  - gcloud auth activate-service-account --key-file service-account.json # login(authorization) to our google cloud account
  - gcloud config set project k8s-multicontainer
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentails k8s-multicontainer
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gulmohar/client -f ./client/Dockerfile.dev ./client

script:
  - docker run gulmohar/client npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
